[package]
name = "flic"
version = "0.1.0"
authors = ["David Wang <millimillenary@gmail.com>"]

[lib]
name = "flic"
crate-type = ["rlib", "dylib"]

[dependencies]
byteorder = "*"
libc = "*"

[dev-dependencies]
sdl2 = "*"
